os: linux
language: node_js
node_js: 12

script:
  - "npm run lint"
  - "npm run build"

deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: dist
  edge: true
  on:
    branch: master