language: node_js
node_js:
  - 12

script:
  - "npm run lint"
  - "npm run clean"
  - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master