language: node_js
node_js:
  - 12

stages:
  - test
  - build
  - deploy

install:
  - "npm install"

script:
  - "npm run lint"
  - "npm run clean"
  - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master